pipeline:
  name: remote_child
  identifier: remote_child
  projectIdentifier: Brijesh
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: cs
        identifier: cs
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 10m
        tags: {}
